# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3'
services:
  truevocation-postgresql:
    image: postgres:14.1
    # volumes:
    #   - ~/volumes/jhipster/truevocation/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=truevocation
      - POSTGRES_PASSWORD=truevocation
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=truevocation
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
